---
title: "Your top tunes!"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.align = 'center',fig.height = 8)
# Loading Libraries and Data-------------------------------------------------------
#Libraries
library(readr)
library(tidyverse)
library(tidytext)
library(ggridges)
library(lexicon)
library(ggtext)
library(here)
library(patchwork)
library(stringr)
library(scales)
library(tools)
library(lexicon)
library(extrafont)
library(showtext)

#Fonts
windowsFonts(`Roboto`=windowsFont("Roboto Condensed"))
font_add_google(name = "Roboto Condensed", family = "Roboto")
showtext_auto()
theme_set(theme_minimal(base_size = 12,base_family="Roboto Condensed"))

#Data
########
#Wrapped Data
########
#Full
  Full_Wrapped <- read_rds(here("data/Full_Wrapped_Feat_Lyrics_Data.rds")) %>% 
    mutate(Wrapped="Yes",
           Playlist=case_when(Playlist=="Your Top Songs 2016"~"2016",
                              Playlist=="Your Top Songs 2017"~"2017",
                              Playlist=="Your Top Songs 2018"~"2018",
                              Playlist=="Your Top Songs 2019"~"2019",
                              Playlist=="Your Top Songs 2020"~"2020"))
  
#Playlist comparison 
  Comparison_Wrapped <- read_rds(here("data/Wrapped_Playlist_Data.rds"))
  Comparison_Wrapped <- Comparison_Wrapped %>% 
    rename("Median Loudness (dB)"=`Median Loudness`,
           "Median Tempo (BPM)"=`Median Tempo`,
           "Percent of Songs That Are Explicit"=`Percent Explicit`) %>% 
    mutate(Wrapped="Yes",
           Playlist=case_when(Playlist=="Your Top Songs 2016"~"2016",
                              Playlist=="Your Top Songs 2017"~"2017",
                              Playlist=="Your Top Songs 2018"~"2018",
                              Playlist=="Your Top Songs 2019"~"2019",
                              Playlist=="Your Top Songs 2020"~"2020"))
  
  
#######
#Top 200
#######
#Full
  Full_Top_200 <- read_rds(here("data/Full_Top_200_Feat_Lyrics_Data.rds"))
  #Adding number of streams
  Jan_2017_Dec_2020 <- read_rds(here("03_Obtain_Top-200-Data/data/Jan_2017_Dec_2020.rds"))
  streams <- Jan_2017_Dec_2020 %>% select(date,"Id"=URI,Streams) %>% distinct()
  Full_Top_200 <- Full_Top_200 %>% left_join(streams)
  Full_Top_200 <- Full_Top_200 %>% mutate(Streams=as.numeric(Streams),
                                          Wrapped="No",
                                          Playlist=as.character(Playlist))
  
#Comparison
  Comparison_Top_200 <- read_rds(here("data/Top200_Weighted_Playlist_Data.rds")) %>% 
    rename("Median Loudness (dB)"=`Median Loudness`,
           "Median Tempo (BPM)"=`Median Tempo`,
           "Percent of Songs That Are Explicit"=`Percent Explicit`) %>% 
    mutate(Wrapped="No",
           `Median Years Since Release (Adj)`=`Median Days Since Release (Adj)`/365) %>% 
    select(-`Median Days Since Release (Adj)`)
  
# Joining Wrapped and Top 200 ---------------------------------------------
  Full_Data <- Full_Wrapped %>% bind_rows(Full_Top_200)
  Full_Comparison <- Comparison_Wrapped %>% bind_rows(Comparison_Top_200)
  
```

```{r Lyric Data}
  Lyrics <- Full_Wrapped %>% select(Playlist,Id,Song,full_lyrics)
  
  words <- Lyrics %>% 
    unnest_tokens(input = full_lyrics,output = "words",token="words",to_lower = F) %>% 
    filter(words!="NA") %>%  #Removing "NA" from the lyrics. This is an artifact of the genius API, which sometimes has the first line as missing
    mutate(words= tolower(words))
```

```{r Add Percent Explicit Words to Comparison data}
#Percent of words explicit in Wrapped
Per_Explicit_Words_Wrapped <- words %>% 
  mutate(explicit=ifelse(words %in% lexicon::profanity_racist | words %in% lexicon::profanity_alvarez,1,0)) %>% 
  group_by(Playlist) %>% 
  summarise(Weighted_Percent_Explicit=mean(explicit,na.rm = T)) %>% 
  mutate(Wrapped="Yes",
         Playlist=as.character(Playlist))

#Percent of Explicit words for top 200
Per_Explicit_Words_Top200 <- read_rds(here("data/Per_Explicit_Words_Top200.rds")) %>% 
  mutate(Wrapped="No", Playlist=as.character(Playlist)) %>% 
  select(-Unweighted_Percent_Explicit)

#Combined percent explicit
Per_Explicit_Words_Combined <- Per_Explicit_Words_Wrapped %>% bind_rows(Per_Explicit_Words_Top200)

#Add to comparison data
Full_Comparison <- Full_Comparison %>% left_join(Per_Explicit_Words_Combined)

```


```{r Music Features}
Feats_Data <- Full_Comparison %>% 
    select(Wrapped,Playlist,`Median Danceability`:`Median Years Since Release (Adj)`,
           `Average Words Per Song`,
           `Percent of Songs That Are Explicit`,
           `Percent of Words That Are Explicit`=Weighted_Percent_Explicit,
           `Percent of Artists Who Are Male`=`Percent Male`) %>% 
    select(-`Median Key (0 is C)`) %>% 
    pivot_longer(`Median Danceability`:`Percent of Songs That Are Explicit`,names_to="Feature") %>% 
    arrange(Wrapped)
  
  Feats_Data %>% 
    ggplot(aes(x=Playlist,y=value)) +
    geom_line(aes(color=Wrapped,group=Wrapped),size=1.5) +
    geom_point(aes(color=Wrapped),size=5) +
    scale_color_manual(values=c("#A9A9A9","#1DB954")) +
    scale_y_continuous(expand = expansion(mult =  0.2)) +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    facet_wrap(~Feature,scales = "free_y",labeller = label_wrap_gen(width = 10)) +
    labs(title="How <span style='color: #1DB954'>**your**</span> music compares to <span style='color: #A9A9A9'>**popular**</span> music",
         subtitle = "Measures such as \"danceability\" are generated by Spotify and used in their internal algorithms",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
    theme(plot.title = element_markdown(size = rel(1.8)),
          plot.subtitle = element_text(size=rel(1),color="grey40", face = "italic"),
          plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
          axis.title = element_blank(),
          plot.title.position = "plot",
          strip.text = element_text(size=rel(.9),face="bold"),
          legend.position = "none")
```

<hr style="border: dashed rgb(128,128,128) 1.0px;background-color: rgb(128,128,128);height: 1.0px;"/>

```{r Genres}
genres <- Full_Comparison %>% select(Wrapped, Playlist,`Percent Hip Hop`:`Percent Other`) 
names(genres) <- names(genres) %>% str_remove("Percent ")

  genres %>% pivot_longer(cols=`Hip Hop`:`Other`,names_to="Genre",values_to="Percent") %>% 
    arrange(Wrapped) %>% 
    ggplot(aes(x=Playlist,y=Percent,group=Wrapped)) +
    geom_line(aes(color=Wrapped),size=1.5) +
    geom_point(aes(color=Wrapped),size=5) +
    scale_color_manual(values=c("#A9A9A9","#1DB954")) +
    scale_y_continuous(expand = expansion(mult =  0.3), n.breaks = 4) +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    facet_wrap(~Genre,scales = "free_y") +
    labs(title="<span style='color: #1DB954'>**Your**</span> favorite genres versus which ones were <br/><span style='color: #A9A9A9'>**popular**</span>",
         subtitle = "Percent of songs in each genre, as classified by Spotify",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
    theme(plot.title = element_markdown(size = rel(1.8)),
          plot.subtitle = element_text(size=rel(1),color="grey40", face = "italic"),
          plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
          axis.title = element_blank(),
          plot.title.position = "plot",
          strip.text = element_text(size=rel(.9),face="bold"),
          legend.position = "none")
```


```{r Sentiment Categories}

  sentiments <- Full_Comparison %>% select(Wrapped,Playlist,`Percent of Words in Trust Category`:`Percent of Words in Anticipation Category`)
  names(sentiments) <- names(sentiments) %>% str_replace("Percent of Words in ","") %>% str_replace(" Category","")
  
  
  sentiments %>% 
    pivot_longer(cols=Trust:Anticipation,
                 names_to="Genre",
                 values_to="Percent") %>% 
    arrange(Wrapped) %>% 
    ggplot(aes(x=Playlist,y=Percent,group=Wrapped)) +
    geom_line(aes(color=Wrapped),size=1.5) +
    geom_point(aes(color=Wrapped),size=5) +
    scale_color_manual(values=c("#A9A9A9","#1DB954")) +
    scale_y_continuous(expand = expansion(mult =  0.2)) +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) + 
    facet_wrap(~Genre,scales = "free_y") +
    labs(title="What were the vibes of <span style='color: #1DB954'>**your**</span> music versus <span style='color: #A9A9A9'>**popular**</span> music",
         subtitle = "Percent of words that fall into given sentiment categories, using NRC lexicon",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
     theme(plot.title = element_markdown(size = rel(1.8)),
           plot.subtitle = element_text(size=rel(1),color="grey40", face = "italic"),
           plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
           axis.title = element_blank(),
           plot.title.position = "plot",
           strip.text = element_text(size=rel(.9),face="bold"),
           legend.position = "none")
```


```{r Overall Sentiment}
# Overall Sentiment -------------------------------------------------
  Full_Comparison %>% 
    select(Wrapped, Playlist, `Average Overall Sentiment`) %>% 
    ggplot(aes(x=Playlist,y=`Average Overall Sentiment`,color=Wrapped,group=Wrapped)) +
    geom_line(size=1.5) +
    geom_point(size=5) +
    geom_hline(yintercept = 0,linetype="dashed") +
    scale_color_manual(values = c("#1DB954","#A9A9A9")) +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    guides(color="none") +
    labs(title="What was the overall sentiment of <span style='color: #1DB954'>**your**</span> music versus <br> <span style='color: #A9A9A9'>**popular**</span> music",
         subtitle = "Using AFINN lexicon",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
    theme(plot.title = element_markdown(size = rel(1.8)),
          plot.subtitle = element_text(colour = "grey50", face = "italic"),
          plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
          axis.title = element_blank(),
          plot.title.position = "plot",
          strip.text = element_text(size=rel(.9),face="bold"),
          legend.position = "none")
```

```{r Top Artists}
 # Top Artists -------------------------------------------------------------
  Artists <- Full_Wrapped %>% 
    count(Playlist,Artist) %>% 
    arrange(desc(n)) %>% 
    group_by(Playlist) %>% 
    top_n(5, n) %>% 
    mutate(Artist=reorder_within(x = Artist,within = Playlist,by = n))
  
  Artists$Playlist <- factor(Artists$Playlist,
                             levels=c("2016","2017","2018","2019","2020"),
                             labels=c("2016","2017","2018","2019","2020"))
  
  ggplot(Artists, aes(Artist, n, fill = Playlist)) +
      geom_col(show.legend = FALSE) +
      labs(x = NULL, y = "count") +
      facet_wrap(~Playlist, ncol = 2, scales = "free_y") +
      coord_flip() +
      scale_x_reordered() +
      scale_fill_manual(values = c("#5BC680","#1DB954","#16873D","#1B3B26")) +
      labs(title="Your Top Artists by Year",
           y="Number of Songs",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
      theme(plot.title = element_text(size = rel(2)),
          plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
            plot.title.position = "plot",
            axis.text.y = element_text(face="bold"))

```



```{r Top Clean Words}
  interesting_words <- words %>% 
    #Removing stop words
    anti_join(stop_words, by=c("words"="word")) %>% 
    #Removing racist and profane words
    anti_join(tibble(words=lexicon::profanity_racist)) %>% 
    anti_join(tibble(words=lexicon::profanity_alvarez)) %>% 
    #Removing more stop words
    filter(!(words %in% c("ya","yea","yeah","oh","ohh","ooh","ay","ayy","uh","gon"))) 
  
  top_5_words <- interesting_words %>% 
    filter(!is.na(words)) %>% 
    count(Playlist,words) %>% 
    arrange(desc(n)) %>% 
    group_by(Playlist) %>% 
    mutate(total=sum(n),
           percent=(n/total)) %>% 
    top_n(5, percent) %>% 
    mutate(words=str_to_title(words)) %>% 
    mutate(words=reorder_within(x = words,within = Playlist,by = percent))
  
  top_5_words$Playlist <- factor(top_5_words$Playlist,
                                 levels=c("2017","2018","2019","2020"),
                                 labels=c("2017","2018","2019","2020"))
  
  
  ggplot(top_5_words, aes(words, percent, fill = Playlist)) +
    geom_col(show.legend = FALSE) +
    labs(x = NULL, y = "percent") +
    facet_wrap(~Playlist, ncol = 2, scales = "free_y") +
    scale_y_continuous(expand = c(0,0),labels = scales::percent) +
    coord_flip() +
    scale_x_reordered() +
    scale_fill_manual(values = c("#5BC680","#1DB954","#16873D","#1B3B26")) +
    labs(title="Your Top Clean Words by Year",
         subtitle = "Not including so-called stop words such as \"the\" and \"for\"",
         y="Percent of all non-stop words",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
    theme(plot.title = element_text(size = rel(2)),
          plot.subtitle = element_text(colour = "grey50", face = "italic"),
          plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
          plot.title.position = "plot",
          axis.text.y = element_text(face="bold"))
```


```{r Top Words Including Explicit}
interesting_words_explicit <- words %>% 
    #Removing stop words
    anti_join(stop_words, by=c("words"="word")) %>% 
    #Removing more stop words
    filter(!(words %in% c("ya","yea","yeah","oh","ohh","ooh","ay","ayy","uh","gon"))) 
  
  top_5_words_explicit <- interesting_words_explicit %>% 
    count(Playlist,words) %>% 
    arrange(desc(n)) %>% 
    group_by(Playlist) %>% 
    mutate(total=sum(n),
           percent=(n/total)*100) %>% 
    top_n(5, percent) %>% 
    mutate(words_clean=toTitleCase(words),
           words_clean=case_when(
             words %in% lexicon::profanity_racist~str_replace_all(string = words_clean,pattern = "A|a|e|i|o|u",replacement = "*"),
             words %in% lexicon::profanity_alvarez~str_replace_all(string = words_clean,pattern = "A|a|e|i|o|u",replacement = "*"),
             TRUE~words_clean)) %>%
    mutate(words_clean=reorder_within(x = words_clean,within = Playlist,by = percent))
  
  top_5_words_explicit$Playlist <- factor(top_5_words_explicit$Playlist,
                                          levels=c("2017","2018","2019","2020"),
                                          labels=c("2017","2018","2019","2020"))

  
  ggplot(top_5_words_explicit, aes(words_clean, percent, fill = Playlist)) +
    geom_col(show.legend = FALSE) +
    labs(x = NULL, y = "percent") +
    facet_wrap(~Playlist, ncol = 2, scales = "free_y") +
    scale_y_continuous(expand = c(0,0)) +
    coord_flip() +
    scale_x_reordered() +
    scale_fill_manual(values = c("#5BC680","#1DB954","#16873D","#1B3B26")) +
    labs(title="Top Words by Year, Including Eplicit Words",
         subtitle = "Not including so-called stop words such as \"the\" and \"for\"",
         y="Percent of all non-stop words",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
    theme(plot.title = element_text(size = rel(2)),
          plot.subtitle = element_text(colour = "grey50", face = "italic"),
          plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
          plot.title.position = "plot",
          axis.text.y = element_text(face="bold"))
```

```{r Most Unique Words by Year}
# Most Unique Words -------------------------------------------------------
  Relative_Importance <- read_rds(here("data/Relative_Importance.rds"))
  
  
  Top_10_Relative_Importance <- Relative_Importance %>% 
    mutate(Playlist=case_when(Playlist=="Your Top Songs 2016"~"2016",
                              Playlist=="Your Top Songs 2017"~"2017",
                              Playlist=="Your Top Songs 2018"~"2018",
                              Playlist=="Your Top Songs 2019"~"2019",
                              Playlist=="Your Top Songs 2020"~"2020")) %>% 
    select(Playlist,word,difference) %>%
    distinct() %>% 
    group_by(Playlist) %>% 
    top_n(5, difference) %>%
    mutate(word_clean=toTitleCase(word),
           word_clean=case_when(
             word %in% lexicon::profanity_racist~str_replace_all(string = word_clean,pattern = "A|a|e|i|o|u",replacement = "*"),
             word %in% lexicon::profanity_alvarez~str_replace_all(string = word_clean,pattern = "A|a|e|i|o|u",replacement = "*"),
             TRUE~word_clean)) %>%
    mutate(word_clean=reorder_within(x = word_clean,within = Playlist,by = difference))
  
  
  
  Top_10_Relative_Importance$Playlist <- factor(Top_10_Relative_Importance$Playlist,
                                                levels=c("2017","2018","2019","2020"),
                                                labels=c("2017","2018","2019","2020"))
  
  Top_10_Relative_Importance %>%
    ggplot(aes(word_clean, difference, fill = Playlist)) +
    geom_col(show.legend = FALSE) +
    labs(x = NULL, y = "count") +
    facet_wrap(~Playlist, ncol = 2, scales = "free_y") +
    scale_y_continuous(expand = c(0,0)) +
    coord_flip() +
    scale_x_reordered() +
    scale_fill_manual(values = c("#5BC680","#1DB954","#16873D","#1B3B26")) +
    labs(title="Most Uniquely Important Words for Each Year",
         subtitle = "% of all words made up by word X in year Y minus % of words made up of word X outside of year Y",
         y="Proportional Importance (Percent)",
         caption = "Plot: @jakepscott2020 | Data: Spotify and Genius") +
    theme_minimal(base_size = 12) +
    theme(plot.title = element_text(size = rel(2)),
          plot.subtitle = element_text(colour = "grey50", face = "italic"),
          plot.caption = element_text(face = "italic", size = rel(0.8), 
                                    color = "grey70"),
          plot.title.position = "plot",
          axis.text.y = element_text(face="bold")) 
```

